apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: shoot-seo

resources:
  - ../../base

images:
  - name: frontend
    newName: europe-central2-docker.pkg.dev/PROJECT_ID/shoot-seo/frontend
    newTag: latest
