apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: shoot-seo

resources:
  - deployment.yaml
  - service.yaml
  - hpa.yaml

commonLabels:
  app.kubernetes.io/part-of: shoot-seo
